### ISSUE TITLE
Class argument completion

### ISSUE THREAD

**Issue by ghost** [nozzergaming/class-complete#1]
I think that it would be a good idea to add argument completion into to the class completion.

You can do `ClassName <Crtl-Shift-Space>` and generate

```
ClassName = (function() {
    function ClassName() {

    }

    return ClassName;
}());
```

I think that it'd be nice to be able to do `ClassName:a,b,c <Crtl-Shift-Space>` and generate

```
ClassName = (function() {
    function ClassName(a, b, c) {

    }

    return ClassName;
}());
```

Also, an extension to that would be to provide type checking and default values, an example would be `ClassName:a,[b,type:number],[c,type:string],[d,class:MyClass,default:new[12, 3]],[e,class:MyClass,default:new],[f,type:number,default:42] <Crtl-Shift-Space>` and generate

```
ClassName = (function() {
    function ClassName(a, b, c, d, e, f) {
        if (typeof b === "number" && typeof c === "string" && (d instanceof MyClass || new MyClass(12, 3)) && (e instanceof MyClass || new MyClass()) && (typeof f === "number" ? f : 42)) {
        } else {
        }
    }

    return ClassName;
}());
```

**Comment by noahbki** [comment]
I have implemented the first suggestion, however the latter can not be implemented at this time as I cannot be bothered to spend a large amount of my time parsing something like that. You are welcome to create a pull request and implement it yourself. ;)
